[workspace]
resolver = "2"
members = ["base64", "hex", "base32",  "digital_ocean", "scaleway", "git-server", "spreadsheet-server", "vectordb"]

[workspace.dependencies]
criterion = { version = "0.7", features = ["html_reports"] }
