[package]
name = "base64"
version = "0.1.0"
edition = "2021"
description = "A library for base64 encoding and decoding"
license = "MIT"

[dependencies]

[dev-dependencies]
criterion = { workspace = true }
base64-external = { workspace = true }

[[bench]]
name = "benchmarks"
harness = false
