# [build]
# Using lld as the linker greatly improve compilation times
[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-cpu=native", "--cfg", "chacha20_force_avx2"]
[target.x86_64-unknown-linux-gnu]
rustflags = ["target-cpu=native", "--cfg", "chacha20_force_avx2"]
